repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        # needed for .gitlab-ci.yaml
        args:
          - --unsafe
      - id: check-added-large-files

  - repo: https://github.com/ambv/black
    rev: 26.1.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [pyproject-flake8]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
        args: [--fix, --ignore,  E741]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        exclude: examples|test|ci
        additional_dependencies: ["pulser-core[torch]>=1.7.0", "torch==2.9.0,<2.11.0"]  # The version in pyproject.toml must match

  - repo: https://github.com/pasqal-io/doc_checker
    rev: 53bb9d79b85d2bdc8ec7ffbc05b97749c3593583 # full SHA for the commit to use
    hooks:
     - id: doc-checker-basic
       args: ["--ignore-submodules", "emu_mps.optimatrix"]
     - id: doc-checker-links
       args: ["--ignore-submodules", "emu_mps.optimatrix"]
       verbose: true
