name: GitHub Actions Demo
run-name: CI/CD for ${{ github.ref_name }}
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - run: echo "hello world!"
  test:
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - run: echo "hello world!"
