name: Lint and test
run-name: CI/CD for ${{ github.ref_name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install pre-commit pyproject-flake8
      - run: pre-commit install
      - run: pre-commit run --all-files
  check_dependency_versions:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python ./test_dependency_versions.py
#  test:
#    needs: check_dependency_versions
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-python@v5
#        with:
#          python-version: ${{ matrix.python-version }}
#      - run: pip install -r test_requirements.txt
#      - run: pip install -e .
#      - run: pytest -vvv --cov-report=term-missing --cov-config=pyproject.toml --cov=emu_mps --cov=emu_base --cov=emu_sv --cov=optimatrix
#      - run: pytest --nbmake -k ipynb
#      - run: readme-cov
  test_ci_pyproject_installs:
    #needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Test CI pyproject installations
        run: |
          for pyproject in emulators/ci/*/pyproject.toml; do
            dir=$(dirname "$pyproject")
            echo "Testing installation from $dir"
            pip install "$dir" || exit 1
          done
