name: Publish emu-sv
run-name: Publish emu-sv

on:
  workflow_run:
    workflows: [Publish emu-base]
    types:
      - completed
concurrency:
  group: fast-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish_emu_sv:
    name: Publish emu-sv to PyPI
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Check emulators
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch
      - name: Build and publish package
        run: |
          cd ci/emu_sv
          hatch build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ github.workspace }}/ci/emu_sv/dist
          verbose: true
